name: fi_toplan
description: Bursa acil durum ve afet toplanma yerleri
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0

  json_annotation: ^4.9.0
  lottie: ^2.7.0
  flutter_map: ^8.1.0
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  url_launcher: ^6.2.5
  shared_preferences: ^2.5.2
  kartal: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/toplanma_alanlari.json